### ISSUE TITLE
Unresolved external symbols with MSVC 2013

### ISSUE THREAD

**Issue by feliwir** [ctabin/libzippp#4] opened 2014-09-16 10:19 UTC
Hi, i did built the library succesfully with MSVC 2013 and i now link against libzippp_static.lib and get the following linker errors:
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_close
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_delete
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_dir_add
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_discard
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_fclose
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_file_add
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_file_get_comment
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_file_rename
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_file_set_comment
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_fopen_index
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_fread
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_get_archive_comment
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_get_num_entries
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_name_locate
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_open
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_set_archive_comment
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_set_default_password
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_source_buffer
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_source_file
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_source_free
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_stat_index
1>libzippp_static.lib(libzippp.obj) : error LNK2001: unresolved external symbol _zip_stat_init

Is this an issue on my side or a bug?

**Comment by ctabin** [comment] 2016-02-02 22:48
Since I did never reproduce the issue and never had any other report about it, I close this...

**Closed by ctabin** 2016-02-02 22:48 UTC
